macOS: Update configure script
* look for libusb with pkg-config support;
* build only x64 arch.

diff --git a/MacOSX/configure b/MacOSX/configure
--- a/MacOSX/configure
+++ b/MacOSX/configure
@@ -19,13 +19,10 @@
 #    02110-1301 USA.
 
 # to use
-# ./MacOSX/configure LIBUSB_CFLAGS="-I/path/to/libusb/includes" LIBUSB_LIBS="-L/path/to/libusb/libs -lusb"
+# ./MacOSX/configure
 # make
 # make install
 # the driver is installed in /usr/libexec/SmartCardServices/drivers
-#
-# Note: by default dynamic linking is chosen. If static linking against libusb is needed,
-# remove libusb.so from /path/to/libusb/libs
 
 # Colors
 RED="\033[31m"
@@ -38,27 +35,26 @@ then
 	echo "ERROR!"
 	echo "run ./MacOSX/configure from the source top directory"
 	echo -e $NORMAL
-	exit;
+	exit -1
 fi
 
 ./MacOSX/convert_reader_h.pl MacOSX/reader.h.in > MacOSX/reader.h
-
-# we define PKG_CONFIG so that pkg-config is not used and PCSC_CFLAGS
-# and PCSC_LIBS are used instead
-PKG_CONFIG="foobar"
 
 # find pcsc-lite header files in MacOSX/
 PCSC_CFLAGS="-I$(pwd)/MacOSX"
 PCSC_LIBS="-framework PCSC"
 
+# use libusb-0.1
+LIBUSB_0_1_DIR=$(pkg-config --variable=libdir libusb)
+LIBUSB_1_0_DIR=$(pkg-config --variable=libdir libusb-1.0)
+LIBUSB_ARCHIVE="${LIBUSB_0_1_DIR}/libusb.a ${LIBUSB_1_0_DIR}/libusb-1.0.a"
+LIBUSB_CFLAGS=$(pkg-config --cflags --static libusb)
+
 # RESPONSECODE is already defined by PCSC/wintypes.h
 # define needed here since config.h is
 # not included
-CFLAGS="-DRESPONSECODE_DEFINED_IN_WINTYPES_H"
+CFLAGS="$CFLAGS -DRESPONSECODE_DEFINED_IN_WINTYPES_H -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
 
-# Build a Universal Binary
-CFLAGS="$CFLAGS -isysroot /Developer/SDKs/MacOSX10.6.sdk -arch i386 -arch x86_64 -arch ppc"
-LDFLAGS="-arch i386 -arch ppc"
 CONFIGURE_ARGS="--disable-dependency-tracking"
 
 # do not use pcscd debug feature
@@ -66,16 +62,21 @@ CONFIGURE_ARGS="$CONFIGURE_ARGS --disable-pcsclite"
 
 set -x
 ./configure \
-	PKG_CONFIG="$PKG_CONFIG" \
 	CFLAGS="$CFLAGS" \
 	PCSC_CFLAGS="$PCSC_CFLAGS" \
 	PCSC_LIBS="$PCSC_LIBS" \
+	LIBUSB_CFLAGS="$LIBUSB_CFLAGS" \
+	LIBUSB_LIBS="$LIBUSB_ARCHIVE" \
 	LDFLAGS="$LDFLAGS" \
-	--enable-usbdropdir=/usr/libexec/SmartCardServices/drivers/ \
+	--enable-usbdropdir=/usr/local/libexec/SmartCardServices/drivers/ \
 	--enable-udevrules=no \
 	$CONFIGURE_ARGS \
 	"$@"
 
+r=$?
+
 # force a regeneration of Info.plist
 rm -f src/Info.plist
 
+# exit with the return code from ./configure
+exit $r
